server:
  port: 8080

spring:
  application:
    name: gateway-api-service

zuul:
  routes:
    users:
      path: /api/users/**
      url: http://localhost:8881/users
    tags:
      path: /api/tags/**
      url: http://localhost:8883/hashtags
