server:
  port: 8080

spring:
  application:
    name: gateway-api-service

zuul:
  prefix: /api
  routes:
    users:
      path: /users/**
      url: http://localhost:8881/users
    tags:
      path: /tags/**
      url: http://localhost:8883/hashtags
    posts:
      path: /internal/posts/**
      url: http://localhost:8882/posts
