language: java

jdk:
  - oraclejdk8

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

addons:
  apt:
    sources:
      - heroku
    packages:
      - heroku-toolbelt

before_script:
  - heroku plugins:install heroku-cli-deploy

script:
  - ./gradlew check
#  - ./gradlew build
  - heroku git:remote -a graal-frontend
  - git push heroku `git subtree split --prefix graal-web-app/dist master`:master --force


deploy:
  skip_cleanup: true
  provider: script
  script: sh deploy/deploy-frontend.sh
  on:
    branch: deploy
