version: '2.1'
services:

  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  eureka-service:
    build: eureka-service
    ports:
      - 8761:8761

  gateway-service:
    build: gateway-service
    ports:
      - 8080:8080

  user-service:
    build: user-service
    ports:
      - 8881:8881

  post-service:
    build: post-service
    ports:
      - 8882:8882

  hashtag-service:
    build: hashtag-service
    ports:
      - 8883:8883

  auth-service:
    build: auth-service
    ports:
      - 8885:8885

  aggregation-service:
    build: aggregation-service
    depends_on:
      - rabbitmq
    ports:
      - 8884:8884

  statistic-service:
    build: statistic-service
    depends_on:
      - rabbitmq
    ports:
      - 8886:8886
