
# common configs
server:
  port: ${PORT:8884}

rabbit-mq:
  tags-stat:
    queue: tags-stat-queue
    exchange: tags-stat-exchange
    routing-key: stat.t

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761}/eureka/

logging:
  level:
    feign: DEBUG


# dev configs
---
spring:
  profiles: dev
  rabbitmq:
    host: rabbitmq
    port: 5671
    username: guest
    password: quest

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true


# cloud configs
---
spring:
  profiles: cloud

  rabbitmq:
    host: ${CLOUD_AMQP_HOST}
    username: ${CLOUD_AMQP_USERNAME}
    password: ${CLOUD_AMQP_PASSWORD}


eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}

