
# common configs
server:
  port: ${PORT:8884}
  rabbitmq: ${RABBITMQ_BIGWIG_TX_URL:amqp://guest:guest@rabbitmq:5672}

rabbit-mq:
  tags-stat:
    queue: tags-stat-queue
    exchange: tags-stat-exchange
    routing-key: stat.t

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761}/eureka/

logging:
  level:
    feign: DEBUG


# dev configs
---
spring:
  profiles: dev

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true


# cloud configs
---
spring:
  profiles: cloud

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}

