
server:
  port: 8080

spring:
  cloud:
    refresh:
      enabled: false

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  prefix: /api/v1

  routes:
    user-aggr-service:
      path: /**
      url: http://aggregation-service:8884/aggr
      sensitiveHeaders:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      url: http://auth-service:8885
      sensitiveHeaders:

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
