
# common configs
server:
  port: ${PORT:8080}

spring:
  cloud:
    refresh:
      enabled: false

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761}/eureka/

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 20000

ribbon:
  ReadTimeout: 20000
  ConnectTimeout: 20000

zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000

  prefix: /api/v1


# dev configs
---
spring:
  profiles: dev

logging:
  level:
    org.springframework.security: INFO

zuul:
  routes:
    user-aggr-service:
      path: /**
      url: http://aggregation-service:8884/aggr
      sensitiveHeaders:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      url: http://auth-service:8885
      sensitiveHeaders:
    statistic-service:
      path: /stats/**
      serviceId: statistic-service
      url: http://statistic-service:8886
      sensitiveHeaders:

eureka:
  instance:
    prefer-ip-address: true


# cloud configs
---
spring:
  profiles: cloud

security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}

zuul:
  routes:
    user-aggr-service:
      path: /**
      url: https://graal-aggregation.herokuapp.com/aggr
      sensitiveHeaders:
    auth-service:
      path: /uaa/**
      serviceId: auth-service
      url: https://graal-auth.herokuapp.com
      sensitiveHeaders:
    statistic-service:
      path: /stats/**
      serviceId: statistic-service
      url: http://graal-statistic.herokuapp.com
      sensitiveHeaders:
