
# common configs
server:
  port: ${PORT:8881}

spring:
  jpa:
    hibernate:
      ddl-auto: update

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761}/eureka/


# dev configs
---
spring:
  profiles: dev

  datasource:
    url: jdbc:h2:file:~/user-db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true


# cloud configs
---
spring:
  profiles: cloud

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

security:
  user:
    password: ${eureka.password}

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}
