server:
  port: 8886

spring:
  application:
    name: statistic-service

  datasource:
    url: jdbc:h2:file:~/stat-db;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: rabbitmq
    port: 5672
    user: guest
    password: guest

rabbit-mq:
  tags-stat:
    queue: tags-stat-queue
    exchange: tags-stat-exchange
    routing-key: stat.t

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://eureka-service:8761/eureka/
