
# common configs
server:
  port: ${PORT:8886}

rabbit-mq:
  tags-stat:
    queue: tags-stat-queue
    exchange: tags-stat-exchange
    routing-key: stat.t

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka-service:8761}/eureka/

logging:
  level:
    feign: DEBUG

spring:
  jpa:
    hibernate:
      ddl-auto: update

# dev configs
---
spring:
  profiles: dev
  rabbitmq:
    host: rabbitmq
    port: 5671
    username: guest
    password: quest

  datasource:
    url: jdbc:h2:file:~/stat-db;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver

logging:
  level:
    org.springframework.security: INFO

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000

eureka:
  instance:
    prefer-ip-address: true


# cloud configs
---
spring:
  profiles: cloud

  rabbitmq:
    host: ${CLOUD_AMQP_HOST}
    virtual-host: ${CLOUD_AMQP_VHOST}
    username: ${CLOUD_AMQP_USERNAME}
    password: ${CLOUD_AMQP_PASSWORD}

  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    url: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true

eureka:
  instance:
    hostname: ${DOMAIN_NAME}
    nonSecurePort: 80
  password: ${USER_PASSWORD:password}

